### PR TITLE
Closes #1. Implement Auth client.

### LINKED ISSUE #1: Create a client that uses auth service

### PR DESCRIPTION
**Pull request by Aleserche**
* Add tests
* Add Exceptions
* Refactoring

### CODE REVIEW

**Review by artemii235 — CHANGES_REQUESTED** [review]
Also it might be nice to add some docker container for development/testing as local php version might be different from required by this repository.

**Review by hlogeon — CHANGES_REQUESTED** [review]
Lets try to implement requested changes first ;)

**Review by artemii235 — CHANGES_REQUESTED** [review]

**Review by hlogeon — CHANGES_REQUESTED** [review]

**Review by hlogeon — COMMENTED** [review]
And I'm not sure about returning `$this` in setters. It looks like you should rename `setId` to `setIdAndReturnSelf`. But it's just only my opinion, take a look on comments to the files

**Review by artemii235 — CHANGES_REQUESTED** [review]

**Review by hlogeon — APPROVED** [review]

**Review by hlogeon — CHANGES_REQUESTED** [review]
Hmmmm

**Review by artemii235 — CHANGES_REQUESTED** [review]

**Review by artemii235 — APPROVED** [review]

**Review by hlogeon — CHANGES_REQUESTED** [review]

**Review by hlogeon — APPROVED** [review]

**Pull request merged**
